services:
  server:
    build: .
    # image: docker.io/kretts/lunar-tear:latest
    volumes:
      - ./assets:/opt/lunar-tear/assets
    ports:
      - 443:443 # grpc, hardcoded by the client, not configurable
      - 8080:8080
    command: 
      - "--host"
      - "127.0.0.1"
      - "--http-port"
      - "8080"
      - "--scene" 
      - "0"