/*
 * Auto-generated by Frida. Please modify to match the signature of send.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`send(socket=${args[0]}, buffer=${args[1]}, length=${args[2]}, flags=${args[3]})`);
  },

  onLeave(log, retval, state) {
  }
});
